config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "homepage#show"

  resources :todos, only: %i( index new create destroy ) do
    resources :todo_items, only: %i( new create show edit update destroy ), module: 'todos'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :todo_items

  accepts_nested_attributes_for :todo_items
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo

  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/todos/todo_items_controller.rb
class Todos::TodoItemsController < ApplicationController
  before_action :set_todo
  before_action :set_todo_item, only: %i( show edit update destroy )

  def new
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.append(
            "todo_#{@todo.id}_todo_items",
            partial: 'todos/todo_items/new',
            locals: { todo: @todo }
          )
        ]
      end
    end
  end

  def show
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(
            "todo_item_#{@todo_item.id}",
            partial: 'todos/todo_items/todo_item',
            locals: { item: @todo_item }
          )
        ]
      end
    end
  end

  def create
    @item = @todo.todo_items.new(todo_item_params)

    if @item.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append(
              "todo_#{@todo.id}_todo_items",
              partial: 'todos/todo_items/todo_item',
              locals: { item: @item }
            ),
            turbo_stream.remove("new_todo_#{@todo.id}_item")
          ]
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(
            "todo_item_#{@todo_item.id}",
            partial: 'todos/todo_items/edit',
            locals: { todo: @todo, todo_item: @todo_item }
          )
        ]
      end
    end
  end

  def update
    if @todo_item.update(todo_item_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(
              "todo_item_#{@todo_item.id}",
              partial: 'todos/todo_items/todo_item',
              locals: { item: @todo_item }
            )
          ]
        end
      end
    end
  end

  def destroy
    @todo_item.destroy
    @todo.reload

    respond_to do |format|
      format.turbo_stream do
        if @todo.todo_items.count <= 0
          @todo.destroy

          render turbo_stream: [
            turbo_stream.remove("todo_#{@todo.id}")
          ]
        else
          render turbo_stream: [
            turbo_stream.remove("todo_item_#{@todo_item.id}")
          ]
        end
      end
    end
  end

  private
    def todo_item_params
      params.require(:todo_item).permit(:description)
    end

    def set_todo
      @todo = Todo.find(params[:todo_id])
    end

    def set_todo_item
      @todo_item = @todo.todo_items.find(params[:id])
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    # sleep 1
    respond_to do |format|
      todos = Todo.includes(:todo_items).all.order(created_at: :desc)

      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(
            "todos-container",
            partial: 'todos/todo',
            collection: todos,
            as: :todo
          )
        ]
      end
    end
  end

  def new
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.prepend(
            "todos-container",
            partial: 'todos/new'
          )
        ]
      end
    end
  end

  def create
    todo = Todo.new(todo_params)

    if todo.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend(
              "todos-container",
              partial: 'todos/todo',
              locals: { todo: todo }
            ),
            turbo_stream.remove("new_todo")
          ]
        end
      end
    end
  end

  def destroy
    @todo.destroy

    respond_to do |f|
      f.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove("todo_#{@todo.id}")
        ]
      end
    end
  end

  private
    def todo_params
      params.require(:todo).permit(todo_items_attributes: [:id, :description, :_destroy])
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/show.html.erb
<%= turbo_frame_tag('homepage') do %>
  <%= content_tag :div, data: { controller: 'loader', loader_target: 'container' }, class: "homepage--container" do %>
    <%= link_to 'Add Todo', new_todo_path, class: 'btn btn-primary', data: { turbo_prefetch: false, turbo_stream: true } %>
    <%= content_tag :div, class: 'container' do %>
      <%= turbo_frame_tag('todos-container', class: 'row mt-3', src: todos_path(format: :turbo_stream)) do %>
        <%= content_tag :div, class: 'align-self-center mx-auto col-xs-12' do %>
          <i class="fa-solid fa-circle-notch fa-spin fa-2xl"></i>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<%= turbo_frame_tag "navbar", data: { controller: 'nav', nav_loader_outlet: '.homepage--text' } do %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
    <%= link_to "Todo", root_path, class: 'navbar-brand', data: { turbo: false } %>
  </nav>
<% end %>

app/views/todos/_new.html.erb
<%= turbo_frame_tag "new_todo", class: 'col-md-4 p-1', data: { controller: 'todo-items', todo_items_target: 'removable' } do %>
  <%= content_tag :div, class: 'card' do %>
    <%= content_tag :div, class: 'card-body' do %>
      <%= form_with url: todos_path, class: 'd-flex gap-2', model: Todo.new, data: { controller: 'form', form_target: 'form', action: 'turbo:submit-end->form#reset' } do |f| %>
        <%= f.fields_for :todo_items, TodoItem.new do |ff| %>
          <%= ff.text_field :description, class: 'form-control', placeholder: 'Todo Description' %>
        <% end %>
        <%= content_tag :div, class: 'd-flex gap-1' do %>
          <%= button_tag class: 'btn btn-primary btn-sm', type: 'submit' do %>
            <i class="fa-solid fa-plus"></i>
          <% end %>
          <%= button_tag class: 'btn btn-danger btn-sm', type: 'button', data: { action: 'click->todo-items#removeElement' } do %>
            <i class="fa-solid fa-xmark"></i>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag dom_id(todo), class: 'col-md-4 p-1' do %>
  <%= content_tag :div, class: 'card' do %>
    <%= content_tag :div, class: 'card-body' do %>
      <%= turbo_frame_tag "todo_#{todo.id}_todo_items" do %>
        <%= render partial: 'todos/todo_items/todo_item', collection: todo.todo_items, as: :item %>
      <% end %>
      <%= link_to new_todo_todo_item_path(todo_id: todo.id), class: 'btn btn-primary btn-sm mt-2', data: { turbo_stream: true } do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/todos/todo_items/_edit.html.erb
<%# Variables: %>
<%# todo %>
<%# todo_item %>
<%= form_with url: todo_todo_item_path(todo_id: todo.id, id: todo_item.id), class: 'd-flex gap-2 mt-2', model: todo_item, data: { controller: 'form', form_target: 'form', action: 'turbo:submit-end->form#reset' } do |f| %>
  <%= f.text_field :description, class: 'form-control form-control-sm', placeholder: 'Todo Description' %>
  <%= content_tag :div, class: 'd-flex gap-1' do %>
      <%= button_tag class: 'btn btn-primary btn-sm', type: 'submit' do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= link_to todo_todo_item_path(todo_id: todo.id, id: todo_item.id), class: 'btn btn-danger btn-sm', data: { turbo_stream: true, turbo_prefetch: true } do %>
        <i class="fa-solid fa-xmark"></i>
      <% end %>
    <% end %>
<% end %>

app/views/todos/todo_items/_new.html.erb
<%# Variables: %>
<%# todo %>
<%= turbo_frame_tag "new_todo_#{todo.id}_item", data: { controller: 'todo-items', todo_items_target: 'removable' } do %>
  <%= form_with url: todo_todo_items_path(todo_id: todo.id), class: 'd-flex gap-2 mt-2', model: todo.todo_items.new, data: { controller: 'form', form_target: 'form', action: 'turbo:submit-end->form#reset' } do |f| %>
    <%= f.text_field :description, class: 'form-control form-control-sm', placeholder: 'Todo Description' %>
    <%= content_tag :div, class: 'd-flex gap-1' do %>
      <%= button_tag class: 'btn btn-primary btn-sm', type: 'submit' do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
      <%= button_tag class: 'btn btn-danger btn-sm', type: 'button', data: { action: 'click->todo-items#removeElement' } do %>
        <i class="fa-solid fa-xmark"></i>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/todos/todo_items/_todo_item.html.erb
<%= turbo_frame_tag dom_id(item), class: 'd-flex gap-3 justify-content-between mb-1', data: { controller: 'todo-items', action: 'mouseover->todo-items#showActions mouseout->todo-items#hideActions' } do %>
  <p class="m-0"><%= item.description %></p>
  <%= content_tag :div, class: 'd-none gap-2', data: { todo_items_target: 'action' } do %>
    <%= link_to edit_todo_todo_item_path(todo_id: item.todo_id, id: item.id), data: { turbo_stream: true }, class: 'text-body' do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
    <%= link_to todo_todo_item_path(todo_id: item.todo_id, id: item.id), data: { turbo_stream: true, turbo_method: :delete }, class: 'text-body' do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
  <% end %>
<% end %>